Repository bpmn-io/diagram-js, pull requests merged in 2019-05, with the labels that each got.

#327 fix(example): add source and target for example connection
  example/app/app.js
Labels: needs review

#333 fix(auto-resize): allow passing hints
  lib/features/auto-resize/AutoResize.js
  test/spec/features/auto-resize/AutoResizeSpec.js
Labels: needs review

#337 fix(move-preview): cleanup preview after move
  lib/features/move/MovePreview.js
  test/spec/features/move/MovePreviewSpec.js
Labels: needs review

#343 chore(create): merge multiple if statements
  lib/features/create/Create.js
Labels: needs review

#345 fix(geometry): reverse truthy return values of `pointsAligned()`
  lib/features/bendpoints/BendpointUtil.js
  lib/features/bendpoints/ConnectionSegmentMove.js
  lib/layout/ManhattanLayout.js
  lib/util/Geometry.js
  test/spec/util/GeometrySpec.js
Labels: needs review

#342 Do Not Attempt Preview If No Target
  lib/features/connection-preview/ConnectionPreview.js
Labels: needs review

#348 docs(core/EventBus): add missing parameter jsdoc for once method
  lib/core/EventBus.js
Labels: documentation

#347 Allow setting and sharing of hints between create and commandStack.shape.create events
  lib/features/create/Create.js
  test/spec/features/create/CreateSpec.js
Labels: enhancement, needs review
