Repository bpmn-io/diagram-js, pull requests merged in 2022-05, with the labels that each got.

#636 fix: comply with style-src CSP
  lib/core/Canvas.js
  lib/features/overlays/Overlays.js
  lib/features/popup-menu/PopupMenu.js
  lib/features/search-pad/SearchPad.js
  lib/features/tooltips/Tooltips.js
  lib/util/Text.js
  package-lock.json
  package.json
  test/spec/features/overlays/OverlaysSpec.js
  test/spec/features/tooltips/TooltipsSpec.js
Labels: needs review

#639 deps: replace inherits with inherits-browser
  karma.conf.js
  lib/command/CommandInterceptor.js
  lib/draw/DefaultRenderer.js
  lib/features/attach-support/AttachSupport.js
  lib/features/auto-resize/AutoResize.js
  lib/features/auto-resize/AutoResizeProvider.js
  lib/features/grid-snapping/behavior/ResizeBehavior.js
  lib/features/label-support/LabelSupport.js
  lib/features/modeling/cmd/CreateLabelHandler.js
  lib/features/ordering/OrderingProvider.js
  lib/features/root-elements/RootElementsBehavior.js
  lib/features/rules/RuleProvider.js
  lib/model/index.js
  package-lock.json
  package.json
  test/spec/command/CommandInterceptorSpec.js
  test/spec/features/attach-support/rules/AttachRules.js
  test/spec/features/auto-resize/AutoResizeSpec.js
  test/spec/features/bendpoints/rules/BendpointRules.js
  test/spec/features/connect/rules/ConnectRules.js
  test/spec/features/copy-paste/rules/CopyPasteRules.js
  test/spec/features/create/rules/CreateRules.js
  test/spec/features/editor-actions/rules/CustomRules.js
  test/spec/features/global-connect/rules/GlobalConnectRules.js
  test/spec/features/grid-snapping/behavior/ResizeBehaviorSpec.js
  test/spec/features/keyboard-move-selection/rules/KeyboardMoveRules.js
  test/spec/features/label-support/rules/LabelSupportRules.js
  test/spec/features/move/renderer/MarkerRenderer.js
  test/spec/features/move/rules/MoveRules.js
  test/spec/features/ordering/provider/TestOrderingProvider.js
  test/spec/features/resize/rules/ResizeRules.js
  test/spec/features/rules/RuleProviderSpec.js
  test/spec/features/rules/priority-rules/PriorityRules.js
  test/spec/features/rules/rules/TestRules.js
  test/spec/features/rules/say-no-rules/SayNoRules.js
  test/spec/features/selection/rules/ConnectRules.js
  test/spec/features/space-tool/auto-resize/CustomAutoResizeProvider.js
  test/spec/features/space-tool/rules/SpaceRules.js
Labels: needs review

#626 Upgrade to `didi@8`
  lib/Diagram.js
  package-lock.json
  package.json
Labels: needs review, spring cleaning

#642 chore(CHANGELOG): update to v8.4.0
  CHANGELOG.md
Labels: needs review

#646 feat(snapping): snap bendpoints on connection path
  lib/features/bendpoints/BendpointSnapping.js
  lib/features/bendpoints/BendpointUtil.js
  lib/features/bendpoints/GeometricUtil.js
  test/spec/features/bendpoints/BendpointsMoveSpec.js
  test/spec/features/bendpoints/GeometricUtilSpec.js
Labels: in progress

#648 fix(modeling): remove incoming/outgoing on `connection.delete`
  lib/features/modeling/cmd/DeleteConnectionHandler.js
  test/spec/features/modeling/DeleteConnectionSpec.js
  test/spec/features/modeling/DeleteElementsSpec.js
Labels: in progress
